nota1 = int(input("Digite a primeira nota:"))
print()
nota2 = int(input("Digite a segunda nota:"))
print()
nota3 = int(input("Digite a terceira nota:"))
print()
nota4 = int(input("Digite a quarta nota:"))
print()
media = nota1 + nota2 + nota3 + nota4 / 4
print("A média aritmética é: ", media)